language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest" APP_ENV="testing" APP_DEBUG=true SQLITE_DATABASE=":memory:" APP_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" BUGSNAG_API_KEY=""'

env:
  - APP_ENV="testing" APP_DEBUG=true SQLITE_DATABASE=":memory:" APP_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" BUGSNAG_API_KEY=""

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source --dev
  - php artisan env
  - php artisan migrate

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/codecept run --coverage --coverage-xml

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml; fi;'

after_failure:
 - cat storage/logs/*.log

notifications:
  webhooks:
    urls:
      secure: "D5Hr3KOzkmiH1F5wcuzJec9T2hiWN+8mXh+NFudhMfPeAxP2F/2w9y/r1kGp/2Ikz4Zn3DupbODz6UoYfh6UkxtrCJQNkch6j/OqAfrROT7cmOvMcQbO67zgZEw4T9xwBCYTpBIujoq8Nzg/NoAbfMCVHw6a4jNZhLD4crLMxr4="
    on_success: always
    on_failure: never
